from setuptools import setup, find_packages

setup(
    name="mev-empire",
    version="1.0.0",
    description="Ultimate Flash Loan MEV Arbitrage System",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="MEV Empire Team",
    author_email="team@mevempire.com",
    url="https://github.com/mev-empire/mev-empire-complete",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.9",
    install_requires=[
        "web3>=6.11.0",
        "asyncio>=3.4.3",
        "aiohttp>=3.9.0",
        "websockets>=12.0",
        "redis>=5.0.0",
        "numpy>=1.24.0",
        "scipy>=1.11.0",
        "pandas>=2.1.0",
        "scikit-learn>=1.3.0",
        "tensorflow>=2.14.0",
        "torch>=2.1.0",
        "psycopg2-binary>=2.9.0",
        "sqlalchemy>=2.0.0",
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "pydantic>=2.5.0",
        "python-dotenv>=1.0.0",
        "ccxt>=4.1.0",
        "flashbots>=1.3.0",
        "cryptography>=41.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "pytest-asyncio>=0.21.0",
            "black>=23.11.0",
            "flake8>=6.1.0",
            "mypy>=1.7.0",
        ],
        "ml": [
            "tensorflow>=2.14.0",
            "torch>=2.1.0",
            "xgboost>=2.0.0",
            "lightgbm>=4.1.0",
            "optuna>=3.4.0",
        ],
        "monitoring": [
            "prometheus-client>=0.19.0",
            "sentry-sdk>=1.38.0",
            "plotly>=5.17.0",
            "dash>=2.14.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "mev-empire=src.main:main",
            "mev-deploy=scripts.deploy_empire:main",
            "mev-monitor=scripts.monitor_empire:main",
        ],
    },
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: Other/Proprietary License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Office/Business :: Financial :: Investment",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords="mev arbitrage defi flash-loans trading cryptocurrency",
    project_urls={
        "Homepage": "https://github.com/mev-empire/mev-empire-complete",
        "Documentation": "https://docs.mevempire.com",
        "Repository": "https://github.com/mev-empire/mev-empire-complete",
        "Issues": "https://github.com/mev-empire/mev-empire-complete/issues",
    },
    include_package_data=True,
    zip_safe=False,
)
